select * from herdin
insert into herdin values('백업테스트', '호호')

--	커맨드
SELECT * FROM ::fn_dblog(default, default)	-- LOG 내용 확인
DBCC SQLPERF(LOGSPACE)		-- 모든 DB 이름, 로그사이즈, 사용률, 상태 확인 
BACKUP LOG [MILES] WITH NO_LOG	-- 로그 내용 지우기 (옵션 NO_LOG)
SP_HELPDB [MILES]			-- 대상 파일 이름 확인
DBCC SHRINKFILE([DT_1229_log], 5, TRUNCATEONLY)	-- 5메가까지 축소
--	변수확인
DECLARE @DBName VARCHAR(50)
DECLARE @strName VARCHAR(50)
DECLARE @strFilename VARCHAR(50)
DECLARE @folderdir VARCHAR(50)
DECLARE @bakDir VARCHAR(50)
SET @folderdir = 'D:'
SET @DBName = 'MILES'
set @strName = N'[' + @DBName + '] ' + convert(varchar(30), getdate(), 21)     
set @strFilename = @folderdir + '\' + @DBName + '\' + @DBName + '_' + left(replace(replace(replace(convert(char(19), getdate(), 120), '-', ''), ':', ''), ' ', ''), 12) + '_F.bak'
set @bakDir = @folderdir + '\' + @DBName
SELECT @DBName, @strName, @strFilename, @folderdir, @bakDir

--	풀백업 형식
BACKUP DATABASE @DBName TO  DISK = @strFilename
WITH NOFORMAT, COMPRESSION, NOINIT,
NAME = @strName, SKIP, REWIND, NOUNLOAD,  STATS = 10 

--	풀백업
BACKUP DATABASE [MILES] TO  DISK = 'D:\MILES_BACKUP_FULL.bak'
WITH NOFORMAT,  NOINIT,
NAME = 'MILES_BACKUP_01', SKIP, REWIND, NOUNLOAD,  STATS = 10  

--	백업 데이터비교 01
SELECT * FROM HERDIN
INSERT INTO HERDIN VALUES( '백업테스트01', '호호')

--	디퍼런셜 백업
BACKUP DATABASE [MILES] TO  DISK = 'D:\MILES_BACKUP_DIFF.bak'
WITH DIFFERENTIAL, NOFORMAT, NOINIT,
NAME = 'MILES_BACKUP_02', SKIP, REWIND, NOUNLOAD,  STATS = 10    

--	백업 데이터비교 02
SELECT * FROM HERDIN
INSERT INTO HERDIN VALUES( '백업테스트02', '호호')


--	디비삭제
USE [MASTER]
USE [MILES]

RESTORE HEADERONLY FROM DISK = 'D:\MILES_BACKUP_FULL.bak'
RESTORE FILELISTONLY FROM DISK = 'D:\MILES_BACKUP_DIFF.bak'

--	복구
RESTORE DATABASE [MILES2]
FROM DISK = 'D:\MILES_BACKUP_FULL.bak'
WITH	MOVE 'DT_1229' TO 'C:\DT_1229_FULL.MDF',
	MOVE 'DT_1229_log' TO 'C:\DT_1229_log_FULL.ldf'
--	확인
USE [MILES2]
SELECT * FROM HERDIN

USE [MASTER]
DROP DATABASE MILES2





------------------여기서부터 다시하자 ㅠ.ㅠ.ㅠ.ㅠㅠGMRNGMRNNG 


USE [MILES]
SELECT COUNT(*) FROM HERDIN
DELETE FROM HERDIN

DECLARE @I INT
SET @I = 0
WHILE @I < 100
BEGIN
	INSERT INTO HERDIN VALUES('TEST', 'TESTTEST')
	SET @I = @I + 1
END
SELECT COUNT(*) FROM HERDIN


BACKUP DATABASE [MILES] TO DISK	= 'D:\MILES_BACKUP.bak' WITH INIT
RESTORE HEADERONLY FROM DISK	= 'D:\MILES_BACKUP.bak' WITH FILE = 1
RESTORE FILELISTONLY FROM DISK	= 'D:\MILES_BACKUP.bak' WITH FILE = 1
RESTORE VERIFYONLY FROM DISK		= 'D:\MILES_BACKUP.bak' WITH FILE = 1

DECLARE @I INT
SET @I = 0
WHILE @I < 100
BEGIN
	INSERT INTO HERDIN VALUES('TEST', 'TESTTEST')
	SET @I = @I + 1
END
SELECT COUNT(*) FROM HERDIN

BACKUP DATABASE [MILES] TO DISK = 'D:\MILES_BACKUP.bak' WITH DIFFERENTIAL, NOINIT
RESTORE HEADERONLY FROM DISK = 'D:\MILES_BACKUP.bak' WITH FILE = 3
RESTORE FILELISTONLY FROM DISK = 'D:\MILES_BACKUP.bak' WITH FILE = 1
RESTORE VERIFYONLY FROM DISK = 'D:\MILES_BACKUP.bak'  WITH FILE = 1

DELETE FROM HERDIN
SELECT COUNT(*) FROM HERDIN
USE [MASTER]
RESTORE DATABASE [MILES] FROM DISK ='D:\MILES_BACKUP.bak' WITH FILE=1, NORECOVERY
RESTORE DATABASE [MILES] FROM DISK ='D:\MILES_BACKUP.bak' WITH FILE=2, NORECOVERY
RESTORE DATABASE [MILES] FROM DISK ='D:\MILES_BACKUP.bak' WITH FILE=3, RECOVERY

USE [MILES]
SELECT COUNT(*) FROM HERDIN

-----------------------------------------------
RESTORE DATABASE [MILES] FROM DISK ='D:\MILES_BACKUP.bak' WITH FILE=4, RECOVERY
SELECT @@ERROR
USE [MILES]
SELECT COUNT(*) FROM HERDIN

CREATE PROC HERDIN_BACKUP_FULL
AS
BEGIN
USE [MASTER]
BACKUP DATABASE [MILES] TO DISK = 'D:\MILES_BACKUP.bak' WITH INIT
END

CREATE PROC HERDIN_BACKUP_DIFF
	@FN	INT
AS
BEGIN

END

CREATE PROC HERDIN_INC_100
AS
BEGIN
DECLARE @I INT
SET @I = 0
WHILE @I < 100
	BEGIN
	INSERT INTO HERDIN VALUES('TEST', 'TESTTEST')
	SET @I = @I + 1
	END
END