# F9			  : EXECUTE ALL
# SHIFT + F9 : EXECUTE SELECTION

#SYSDATE FORMATER
SELECT DATE_FORMAT(SYSDATE(), '%Y%m%d%H%i%s') FROM DUAL

#SEQ IMPLEMENT
DESC SEQ_TEST;
INSERT INTO SEQ_TEST VALUES();
SELECT MAX(SEQ_NUM) FROM SEQ_TEST;

SELECT * FROM SEQ_TEST
DELETE FROM SEQ_TEST

ALTER TABLE SEQ_TEST AUTO_INCREMENT = 1

