-- SELECT ALL TABLE COLUMNS
SELECT * FROM ALL_TAB_COLUMNS
-- SELECT ALL CONSTRAINT WITH COLUMNS
SELECT * FROM ALL_CONS_COLUMNS
-- SELECT ALL CONSTRAINTS
SELECT * FROM ALL_CONSTRAINTS

-- INPUT YOUR TABLE NAME TO 'TABLE_NAME
WITH TABLENAME AS(SELECT 'TABLE_NAME' AS "TARGET TABLE name" FROM DUAL)
SELECT COLUMN_NAME           || ' & ' ||
       DATA_TYPE             || ' & ' ||
       DECODE(NULLABLE, 'N', 'NO', 'Y', 'YES')         || ' & ' ||
       MARK                  || ' & ' ||
       ' '                   || ' & ' ||
       ' '                   || '\\' AS INPUT_DATA
FROM ALL_TAB_COLUMNS ATC
LEFT JOIN 
     (
    SELECT COLUMN_NAME AS PRIMARY_COLUMN_NAME,
           'PRI' AS MARK
    FROM ALL_CONS_COLUMNS ACC
    WHERE ACC.TABLE_NAME = (SELECT * FROM TABLENAME) AND
          ACC.CONSTRAINT_NAME = 
                          (SELECT AC.CONSTRAINT_NAME
                          FROM ALL_CONSTRAINTS AC
                          WHERE AC.TABLE_NAME = (SELECT * FROM TABLENAME)   AND
                                AC.CONSTRAINT_TYPE = 'P')
     ) PK ON ATC.COLUMN_NAME = PK.PRIMARY_COLUMN_NAME
WHERE ATC.TABLE_NAME = (SELECT * FROM TABLENAME);